-- https://www.hackerrank.com/challenges/weather-observation-station-5

SELECT * FROM ( SELECT TOP 1 CITY, LEN(CITY) AS Length
FROM STATION
WHERE LEN(CITY) = (SELECT MAX(LEN(CITY)) FROM STATION)
ORDER BY LEN(CITY), CITY ASC) Longest
UNION
SELECT * FROM ( SELECT TOP 1 CITY, LEN(CITY) AS Length
FROM STATION
WHERE LEN(CITY) = (SELECT TOP 1 MIN(LEN(CITY)) FROM STATION) 
ORDER BY LEN(CITY), CITY ASC) Shortest